### ISSUE TITLE
Exceptions throw on meteor startup

### ISSUE THREAD

**Issue by aadamsx** [brentjanderson/meteor-buzz#14]
on staring meteor exceptions are thrown: 

TypeError: Cannot read property 'BUZZ' of undefined
at packages/global-imports.js:21:38
at Array.forEach (native)
W20151217-12:20:58.971(-6)? (STDERR)     at Function._.each._.forEach (/Users/aadams/.meteor/packages/meteor-tool/.1.1.4.remwzz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
t /Users/aadams/Meteors/clients-workstation/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8

I had to uninstall.  Is this not compatible with Meteor 1.2?

**Comment by aadamsx** [comment]
@vjau I see you're a contributor, do you have this project in a more recent version of Meteor, like version 1.2?

**Comment by vjau** [comment]
I'm using it sucessfully with 1.2.
However i'm seeing a cordova related error, are you using Cordova ? 
I'm on Linux.

**Comment by brentjanderson** [comment]
The package works fine in a basic browser/server meteor app. I'm testing with Cordova for iOS and Android now...

**Comment by aadamsx** [comment]
Thanks for looking into this.  I'm trying this out on Meteor 1.1.0.3

This are the steps I take: 

```
> meteor add brentjanderson:buzz
> meteor
> 
TypeError: Cannot read property 'BUZZ' of undefined
at packages/global-imports.js:21:38
at /Users/aadams/Meteors/clients-workstation/.meteor/local/build/programs/server/boot.js:222:10
... ...
at Function._.each._.forEach (/Users/aadams/.meteor/packages/meteor-tool/.1.1.4.remwzz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11
... ...
=> Exited with code: 8
```

**Comment by brentjanderson** [comment]
What do you get when you run `meteor list-platforms` and `meteor list` ?

**Comment by aadamsx** [comment]
```
> meteor list-platforms
browser
server
```

```
> meteor list
255kb:meteor-status           1.4.0* Meteor Status automatically alerts users...
aadams:progress               0.0.4  Animated, responsive progress bar
aadams:quilljs                0.0.1  Quill.js version 0.20.1 for Meteor
accounts-password             1.1.1* Password support for accounts
alanning:roles                1.2.13* Role-based authorization
aldeed:autoform               5.4.0* Easily create forms with automatic inser...
aldeed:collection2            2.3.2* Automatic validation of insert and updat...
aldeed:simple-schema          1.3.0* A simple schema validation object with r...
bigdsk:inputmask              3.1.63  JQuery InputMask for Meteor
chrismbeckett:toastr          2.1.2_1  Gnome / Growl type non-blocking notifi...
edgee:slingshot               0.7.1  Directly post files to cloud storage ser...
email                         1.0.6* Send email messages
fortawesome:fontawesome       4.4.0* Font Awesome (official): 500+ scalable v...
ian:accounts-ui-bootstrap-3   1.2.76* Bootstrap-styled accounts-ui with multi...
ian:bootstrap-3               3.3.1  HTML, CSS, and JS framework for developi...
iron:router                   1.0.9* Routing specifically designed for Meteor
lookback:tooltips             0.5.2  Reactive tooltips.
maazalik:highcharts           0.4.0  HighCharts for Meteor, with an easy to u...
maazalik:highcharts-gauge     0.4.0  HighCharts gauge for Meteor
meteor-platform               1.2.2* Include a standard set of Meteor package...
meteorhacks:aggregate         1.3.0  Proper MongoDB aggregations support for ...
meteortoys:allthings          2.0.0* Insanely Handy Development Tools for Meteor
mizzao:bootboxjs              4.4.0  Programmatic dialog boxes using Twitter'...
mizzao:user-status            0.6.5* User connection and idle state tracking ...
momentjs:moment               2.10.6  Moment.js (official): parse, validate, ...
mrt:cookies                   0.3.0  Basic cookies support for client
mrt:nprogress                 0.2.0  NProgress for Meteor
peerlibrary:aws-sdk           2.1.47_1* SDK for AWS services including Amazon...
reactive-dict                 1.1.0* Reactive dictionary
reactive-var                  1.0.5* Reactive variable
risul:accounting              1.0.1  Meteor package for Accounting.js - http:...
rwatts:meteordump             0.1.0* Dumps variables and objects to the brows...
sacha:spin                    2.3.1  Simple spinner package for Meteor
templates:tabs                2.2.0  Reactive tabbed interfaces compatible wi...
thepumpinglemma:cookies       1.0.0  Meteor package that wrap the cookies pac...
tmeasday:publish-counts       0.7.2  Publish the count of a cursor, in real time
u2622:persistent-session      0.4.3* Persistently store Session data on the c...
vazco:universe-html-purifier  1.2.3  Package to sanitize HTML from untrusted ...
xmlbuilder                    2.4.6* An XML builder for node.js similar to ja...
yasinuslu:blaze-meta          0.3.1* Blaze-meta makes it super simple to mana
```

**Comment by brentjanderson** [comment]
Did you add brentjanderson:buzz to your package list, or are you using it as a dependency to a package? I'm not seeing this package in your package list.

**Comment by aadamsx** [comment]
I just removed it before you asked me to do a meteor list, here it is again with brentjanderson:buzz:

```
255kb:meteor-status           1.4.0* Meteor Status automatically alerts users...
aadams:progress               0.0.4  Animated, responsive progress bar
aadams:quilljs                0.0.1  Quill.js version 0.20.1 for Meteor
accounts-password             1.1.1* Password support for accounts
alanning:roles                1.2.13* Role-based authorization
aldeed:autoform               5.4.0* Easily create forms with automatic inser...
aldeed:collection2            2.3.2* Automatic validation of insert and updat...
aldeed:simple-schema          1.3.0* A simple schema validation object with r...
bigdsk:inputmask              3.1.63  JQuery InputMask for Meteor
brentjanderson:buzz           1.1.10  The fantastic Buzz javascript sound lib...
chrismbeckett:toastr          2.1.2_1  Gnome / Growl type non-blocking notifi...
edgee:slingshot               0.7.1  Directly post files to cloud storage ser...
email                         1.0.6* Send email messages
fortawesome:fontawesome       4.4.0* Font Awesome (official): 500+ scalable v...
ian:accounts-ui-bootstrap-3   1.2.76* Bootstrap-styled accounts-ui with multi...
ian:bootstrap-3               3.3.1  HTML, CSS, and JS framework for developi...
iron:router                   1.0.9* Routing specifically designed for Meteor
lookback:tooltips             0.5.2  Reactive tooltips.
maazalik:highcharts           0.4.0  HighCharts for Meteor, with an easy to u...
maazalik:highcharts-gauge     0.4.0  HighCharts gauge for Meteor
meteor-platform               1.2.2* Include a standard set of Meteor package...
meteorhacks:aggregate         1.3.0  Proper MongoDB aggregations support for ...
meteortoys:allthings          2.0.0* Insanely Handy Development Tools for Meteor
mizzao:bootboxjs              4.4.0  Programmatic dialog boxes using Twitter'...
mizzao:user-status            0.6.5* User connection and idle state tracking ...
momentjs:moment               2.10.6  Moment.js (official): parse, validate, ...
mrt:cookies                   0.3.0  Basic cookies support for client
mrt:nprogress                 0.2.0  NProgress for Meteor
peerlibrary:aws-sdk           2.1.47_1* SDK for AWS services including Amazon...
reactive-dict                 1.1.0* Reactive dictionary
reactive-var                  1.0.5* Reactive variable
risul:accounting              1.0.1  Meteor package for Accounting.js - http:...
rwatts:meteordump             0.1.0* Dumps variables and objects to the brows...
sacha:spin                    2.3.1  Simple spinner package for Meteor
templates:tabs                2.2.0  Reactive tabbed interfaces compatible wi...
thepumpinglemma:cookies       1.0.0  Meteor package that wrap the cookies pac...
tmeasday:publish-counts       0.7.2  Publish the count of a cursor, in real time
u2622:persistent-session      0.4.3* Persistently store Session data on the c...
vazco:universe-html-purifier  1.2.3  Package to sanitize HTML from untrusted ...
xmlbuilder                    2.4.6* An XML builder for node.js similar to ja...
yasinuslu:blaze-meta          0.3.1* Blaze-meta makes it super simple to mana...
```
